name: Docker Apache Drill CI

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:

  make-docker-images:
    name: Build Apache Drill Docker image for SOGIS
    runs-on: ubuntu-20.04
    env:
      DOCKER_ACCOUNT: sogis
      DOCKER_REPO: drill
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}} 
      BUILD_NUMBER: ${{ github.run_number }}
      VERSION: 1.21.1
      DRILL_VERSION: 1.21.1

    steps:

    - name: Set up QEMU for amd64 and arm64
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/amd64,linux/arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}
        labels: |
          org.opencontainers.image.title=drill
          org.opencontainers.image.version=${{ env.VERSION }}
          org.opencontainers.image.base.name=eclipse-temurin:11.0.19_7-jdk-jammy

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      if: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}

    - name: Multi-platform build and push
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        labels: ${{ steps.meta.outputs.labels }}
        pull: true
        push: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}
        tags: |
            ${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:latest
            ${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:${{ env.VERSION }}